language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - cd agent
  - python -m pytest ../tests
  - cd ..
  - sh build.sh

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "ia-agent"
  skip_cleanup: true
  on:
    tags: true
